language: java
sudo: required
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
services:
  - docker

env:
  global:
  - secure: "encrypted-dockerhub-username"
  - secure: "encrypted-dockerhub-password"
  
after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - docker build -t anveshrao3/springSecurity .
    - docker push anveshrao3/springSecurity      