language: java
sudo: required
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
services:
  - docker

env:
  global:
  - secure: "encrypted-dockerhub-username"
  - secure: "encrypted-dockerhub-password"
  - COMMIT=${TRAVIS_COMMIT::7}
  
after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - export IMAGE_NAME=anveshrao3/springSecurity
    - docker build -t $IMAGE_NAME:$COMMIT .
    - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
    - docker push $IMAGE_NAME      